//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Resources.ResShared", typeof(ResShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información no válida.
        /// </summary>
        public static string ERROR_INVALID_MODEL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro no encontrado.
        /// </summary>
        public static string ERROR_MODEL_NOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_MODEL_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido.
        /// </summary>
        public static string ERROR_UNKOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro almacenado exitosamente.
        /// </summary>
        public static string INFO_REGISTER_SAVED {
            get {
                return ResourceManager.GetString("INFO_REGISTER_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC 3.
        /// </summary>
        public static string TITLE_APP_LARGE_NAME {
            get {
                return ResourceManager.GetString("TITLE_APP_LARGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC 3.
        /// </summary>
        public static string TITLE_APP_NAME {
            get {
                return ResourceManager.GetString("TITLE_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación fallida.
        /// </summary>
        public static string TITLE_OBSOLETE_FAILED {
            get {
                return ResourceManager.GetString("TITLE_OBSOLETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación exitosa.
        /// </summary>
        public static string TITLE_OBSOLETE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_OBSOLETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro fallido.
        /// </summary>
        public static string TITLE_REGISTER_FAILED {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        public static string TITLE_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_SUCCESS", resourceCulture);
            }
        }
    }
}
