//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entitties
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetNodeSiteMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetNodeSiteMap()
        {
            this.AspNetPermissionNodePerRole = new HashSet<AspNetPermissionNodePerRole>();
        }
    
        public int Id { get; set; }
        public string NodeName { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public Nullable<int> Parent { get; set; }
        public int NodeType { get; set; }
        public string Icon { get; set; }
        public bool IsLeaf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetPermissionNodePerRole> AspNetPermissionNodePerRole { get; set; }
    }
}
