//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Entitties
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetPermissionNodePerRole
    {
        public int Id { get; set; }
        public int NodeId { get; set; }
        public int RoleId { get; set; }
        public int Permision { get; set; }
    
        public virtual AspNetNodeSiteMap AspNetNodeSiteMap { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
